// Demo data for the LOCAL D1 database: `npm run db:seed:local` (after db:migrate:local).
// Prints SQL to stdout. Deterministic; re-running replaces only the seeded rows
// (ids >= 900000, plaid ids 'local-seed-*'), so anything you link in Sandbox is kept.
// Plaid sign convention: POSITIVE amount = money out. Amounts are stored in cents.

const DAYS = 120;
let s = 42;                                     // mulberry32: small, seedable PRNG
const rand = () => {
  s |= 0; s = (s + 0x6d2b79f5) | 0;
  let t = Math.imul(s ^ (s >>> 15), 1 | s);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const uniform = (lo, hi) => lo + (hi - lo) * rand();
const randrange = (n) => Math.floor(rand() * n);
const pick = (xs) => xs[randrange(xs.length)];
const cents = (dollars) => Math.round(dollars * 100);
const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replaceAll("'", "''")}'`);
const today = new Date();
const isoDay = (daysAgo) => new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate() - daysAgo)).toISOString().slice(0, 10);

// owner, plaid_account, institution, accounts [name, mask, type, subtype, balance]
const ITEMS = [
  ["me", "me_primary", "Chase", [["Chase Total Checking", "4821", "depository", "checking", 6240.18],
                                 ["Chase Sapphire Preferred", "9912", "credit", "credit card", 1284.55]]],
  ["me", "me_primary", "American Express", [["Blue Cash Everyday", "1005", "credit", "credit card", 412.90]]],
  ["me", "me_primary", "Fidelity", [["Cash Management", "7730", "depository", "cash management", 18950.00]]],
  ["spouse", "spouse_primary", "Bank of America", [["Adv Plus Banking", "3317", "depository", "checking", 4102.77],
                                                   ["Customized Cash Rewards", "6604", "credit", "credit card", 689.31]]],
  ["spouse", "spouse_primary", "Ally Bank", [["Online Savings", "2290", "depository", "savings", 22500.00]]],
];

// merchant, category, [min, max], times per 30 days, card-only?
const MERCHANTS = [
  ["Whole Foods Market", "FOOD_AND_DRINK", [35, 180], 5, true],
  ["Trader Joe's", "FOOD_AND_DRINK", [20, 110], 4, true],
  ["Blue Bottle Coffee", "FOOD_AND_DRINK", [4, 14], 8, true],
  ["DoorDash", "FOOD_AND_DRINK", [22, 75], 3, true],
  ["Shell", "TRANSPORTATION", [40, 85], 3, true],
  ["Uber", "TRANSPORTATION", [9, 48], 3, true],
  ["Caltrain", "TRANSPORTATION", [4, 12], 4, true],
  ["Amazon", "GENERAL_MERCHANDISE", [12, 220], 5, true],
  ["Target", "GENERAL_MERCHANDISE", [18, 140], 2, true],
  ["Netflix", "ENTERTAINMENT", [15.49, 15.49], 1, true],
  ["Spotify", "ENTERTAINMENT", [11.99, 11.99], 1, true],
  ["CVS Pharmacy", "MEDICAL", [8, 60], 1, true],
  ["PG&E", "RENT_AND_UTILITIES", [90, 210], 1, false],
  ["Comcast Xfinity", "RENT_AND_UTILITIES", [79.99, 79.99], 1, false],
];
const TAG_POOL = ["groceries", "eating-out", "commute", "subscriptions", "household", "reimbursable"];
const NO_MERCHANT = new Set(["INCOME", "TRANSFER_IN", "TRANSFER_OUT", "LOAN_PAYMENTS"]);

const out = [
  "-- generated by scripts/seed.mjs",
  "DELETE FROM transaction_tags WHERE transaction_id >= 900000;",
  "DELETE FROM transactions WHERE id >= 900000;",
  "DELETE FROM accounts WHERE id >= 900000;",
  "DELETE FROM items WHERE id >= 900000;",
];
let nItems = 0, nAccts = 0, nTxns = 0, txnId = 900000, acctId = 900000;

ITEMS.forEach(([owner, plaidAccount, inst, accts], i) => {
  const itemId = 900000 + i;
  nItems++;
  // Not a real token, so status 'demo': the cron sync only picks up 'good' / 'login_required' Items.
  out.push(`INSERT INTO items (id, owner, plaid_account, plaid_item_id, access_token_enc, institution_name, txn_cursor, status)
            VALUES (${itemId}, ${q(owner)}, ${q(plaidAccount)}, ${q(`local-seed-item-${i}`)}, 'seed-placeholder', ${q(inst)}, 'seed-cursor', 'demo');`);
  accts.forEach(([name, mask, type, subtype, bal], j) => {
    const aId = acctId++;
    nAccts++;
    out.push(`INSERT INTO accounts (id, owner, item_id, plaid_account_id, name, mask, type, subtype, balance_current_cents, balance_available_cents, currency)
              VALUES (${aId}, ${q(owner)}, ${itemId}, ${q(`local-seed-acct-${i}-${j}`)}, ${q(name)}, ${q(mask)}, ${q(type)}, ${q(subtype)}, ${cents(bal)}, ${type === "credit" ? "NULL" : cents(bal)}, 'USD');`);
    const rows = [];
    if (type === "credit") {
      for (const [merchant, cat, [lo, hi], per30] of MERCHANTS) {
        const n = Math.round(per30 * DAYS / 30 * uniform(0.3, 0.7));
        for (let k = 0; k < n; k++) rows.push([merchant, cat, uniform(lo, hi), randrange(DAYS)]);
      }
      rows.push([`${inst} Card Payment - Thank You`, "LOAN_PAYMENTS", -uniform(800, 2500), 12]);
    } else if (subtype === "checking") {
      for (let d = 0; d < DAYS; d += 14) {
        rows.push([owner === "me" ? "ACME Corp Payroll" : "Stanford Univ Payroll", "INCOME", -uniform(3900, 4300), d + 3]);
      }
      for (let d = 0; d < DAYS; d += 30) rows.push(["Rent - Parkside Apartments", "RENT_AND_UTILITIES", 2850, d + 1]);
      for (const [merchant, cat, [lo, hi], , cardOnly] of MERCHANTS) {
        if (!cardOnly) for (let d = 0; d < DAYS; d += 30) rows.push([merchant, cat, uniform(lo, hi), d + 8]);
      }
      rows.push(["Venmo", "TRANSFER_OUT", uniform(20, 150), randrange(DAYS)]);
      rows.push(["Zelle from Alex Chen", "TRANSFER_IN", -120, randrange(DAYS)]);
    } else {
      for (let d = 0; d < DAYS; d += 30) rows.push(["Interest Payment", "INCOME", -uniform(30, 75), d + 28]);
      rows.push(["Transfer from Checking", "TRANSFER_IN", -1000, 40]);
    }

    for (const [merchant, cat, amt, daysAgo] of rows) {
      if (daysAgo >= DAYS) continue;
      const id = txnId++;
      nTxns++;
      let tags = [];
      if (cat === "FOOD_AND_DRINK" && rand() < 0.5) {
        tags = [merchant.includes("Market") || merchant.includes("Joe") ? "groceries" : "eating-out"];
      } else if (cat === "ENTERTAINMENT") {
        tags = ["subscriptions"];
      } else if (rand() < 0.05) {
        tags = [pick(TAG_POOL)];
      }
      const date = isoDay(daysAgo);
      const datetime = `${date}T${String(7 + randrange(15)).padStart(2, "0")}:${String(randrange(60)).padStart(2, "0")}:00Z`;
      const name = rand() < 0.3 ? merchant.toUpperCase() : merchant;
      const pending = daysAgo <= 2 && rand() < 0.6 ? 1 : 0;
      out.push(`INSERT INTO transactions (id, owner, account_id, plaid_txn_id, amount_cents, currency, date, datetime, name, merchant_name, category, pending)
                VALUES (${id}, ${q(owner)}, ${aId}, ${q(`local-seed-txn-${id}`)}, ${cents(amt)}, 'USD', ${q(date)}, ${q(datetime)}, ${q(name)}, ${NO_MERCHANT.has(cat) ? "NULL" : q(merchant)}, ${q(cat)}, ${pending});`);
      tags.forEach((tag, pos) => out.push(`INSERT INTO transaction_tags (transaction_id, tag, position) VALUES (${id}, ${q(tag)}, ${pos});`));
    }
  });
});

process.stdout.write(out.join("\n") + "\n");
process.stderr.write(`seed: ${nItems} items, ${nAccts} accounts, ${nTxns} transactions (last ${DAYS} days)\n`);
